server_public:
  host: f457-103-234-158-46.ngrok-free.app
  port: 8080
  username: tenant@thingsboard.org
  password: tenant

tenants:
  tidly:
    edge: 192.168.0.108
    port: 8080
    username: tenant@thingsboard.org
    password: tenant
    anchors:
      kitchen: edcca8e0-5d00-11ee-9c57-339635acbaee
      entry: 46b94ad0-5cf7-11ee-9c57-339635acbaee
    HumanTags:
      akshay: 00:8c:10:30:02:6f